# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65cf8fe309a9e50fe7efb0c3b2315fc1fa0f0f996fd39923a9917dd6e80b02da0b0afd0022d430b5bdf894c1987b7892f2db079613b43beaf8953ae775036e12

test:
  secret_key_base: b5d4715c2a6f0c64eb198c150d0e62ddd1cafd96be9c73ac33ec5ec830da78252c36f0f87364e7d76dc4a117aa353f1daeacbccae0633d4bedd8d8862ed27508

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
